version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zoopeeker
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "investmentRequestInput:1:1,generateReportInput:1:1,generateReportOutput:1:1,errorLogging:1:1"