server:
  port: 8081
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: com.stockinvestor.dto
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.stockinvestor.dto
  cloud:
    function:
      definition: consumerFunction;
    stream:
      bindings:
        consumerFunction-in-0:
          destination: investmentRequestInput
          contentType: application/json
          consumer:
            useNativeEncoding: true
        consumerFunction-out-0:
          destination: generateReportInput
          contentType: application/json
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          brokers: localhost:9092